# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    # environment:
    #   # Customize the JVM maximum heap limit
    #   MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install awscli
            aws --version
      - run:
          name: Build JAR
          command: |
            cd webapp/restapi
            mvn package
      - run:
          name: Zip JAR File
          command: |
            cd webapp/restapi/target
            zip application.zip restapi.jar
      - run:
          name: Upload ZIP to S3 bucket
          command: |
            aws s3 cp webapp/restapi/target/application.zip s3://code-deploy.csye6225-spring2019-dandekars.me/application.zip       